add missing dependency to jdk-tool
since jenkins-2.112, the JDKInstaller was  moved out to a separate
plugin (jdk-tool), therefore plugins that use this now need to depend
on that plugin.

Missing that plugin causes exceptions like this:
java.lang.ClassNotFoundException: hudson.tools.JDKInstaller

See:
https://issues.jenkins-ci.org/browse/JENKINS-22367
https://issues.jenkins-ci.org/browse/JENKINS-50272